---
version: "3.9"

name: "iotics-connector-example"

x-common-logging:
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "3"

services:
  # Publisher Connector
  publisher:
    container_name: "publisher"
    build:
      context: ".."
      dockerfile: "iotics-connector-example-publisher/Dockerfile"
    command: "python3 /home/iotics/app/main.py"
    env_file:
      - ".env"
    networks: ["connector-example"]
  
  # Follower Connector
  follower:
    container_name: "follower"
    build:
      context: ".."
      dockerfile: "iotics-connector-example-follower/Dockerfile"
    command: "python3 /home/iotics/app/main.py"
    env_file:
      - ".env"
    networks: ["connector-example"]
  
networks:
  connector-example:
    name: "iotics-connector-example"
