---
version: "3.9"

name: "iotics-connector-example"

x-common-logging:
  driver: "json-file"
  options:
    max-size: "100m"
    max-file: "3"

services:
  ngn:
    container_name: "follower"
    build:
      context: ".."
      dockerfile: "iotics-connector-ngn-follower/Dockerfile"
    command: "python3 /home/iotics/app/main.py"
    env_file:
      - ".env"
    ports:
      - "5000:5000"
    networks: ["connector-example"]

networks:
  connector-example:
    name: "iotics-connector-example"

